[
  {
    id: 78,
    name: "Ata Tân thủy thủ",
    price: 39,
    tag: "A",
  },
  {
    id: 79,
    name: "Aya Hoạt náo viên",
    price: 39,
    tag: "A",
  },
  {
    id: 80,
    name: "Bright Soái ca thánh điện",
    price: 39,
    tag: "A",
  },
  {
    id: 84,
    name: "Dextra Chiến binh quyến rũ",
    price: 39,
    tag: "A",
  },
  {
    id: 87,
    name: "Hayate Bạch ảnh",
    price: 39,
    tag: "A",
  },
  {
    id: 89,
    name: "Keera Y tá lạ",
    price: 39,
    tag: "A",
  },
  {
    id: 90,
    name: "Krixi Công Chúa Bướm",
    price: 39,
    tag: "A",
  },
  {
    id: 92,
    name: "Laville Tay đua đường phố",
    price: 39,
    tag: "A",
  },
  {
    id: 93,
    name: "Lorion Chiến giáp hắc ám",
    price: 39,
    tag: "A",
  },
  {
    id: 94,
    name: "Paine Khúc nhạc tử vong",
    price: 39,
    tag: "A",
  },
  {
    id: 96,
    name: "Rouie Sứ giả vũ trụ",
    price: 39,
    tag: "A",
  },
  {
    id: 97,
    name: "Sinestrea Giấc mơ trưa",
    price: 39,
    tag: "A",
  },
  {
    id: 98,
    name: "Tachi Lãng khách",
    price: 39,
    tag: "A",
  },
  {
    id: 99,
    name: "Thorne Cận vệ hoàng gia",
    price: 39,
    tag: "A",
  },
  {
    id: 101,
    name: "Veera Thiên nga đen",
    price: 39,
    tag: "A",
  },
  {
    id: 104,
    name: "Yue Tiểu công Chúa",
    price: 39,
    tag: "A",
  },
  {
    id: 105,
    name: "Zata Tư lệnh viễn chinh",
    price: 39,
    tag: "A",
  },
  {
    id: 106,
    name: "Zip Gà siêu quậy",
    price: 39,
    tag: "A",
  },
  {
    id: 81,
    name: "Capheny Hầu gái",
    price: 41,
    tag: "A",
  },
  {
    id: 82,
    name: "Celica Nữ cao bồi",
    price: 41,
    tag: "A",
  },
  {
    id: 83,
    name: "D'Arcy Nam tước",
    price: 41,
    tag: "A",
  },
  {
    id: 85,
    name: "Enzo Phẩm chất quý tộc",
    price: 41,
    tag: "A",
  },
  {
    id: 86,
    name: "Errol Vượt ngục",
    price: 41,
    tag: "A",
  },
  {
    id: 91,
    name: "Krizzix Cún siêu quậy",
    price: 41,
    tag: "A",
  },
  {
    id: 95,
    name: "Qi Tiểu long",
    price: 41,
    tag: "A",
  },
  {
    id: 100,
    name: "Toro Đặc Cảnh NYPD",
    price: 41,
    tag: "A",
  },
  {
    id: 102,
    name: "Veres Đạo tặc",
    price: 41,
    tag: "A",
  },
  {
    id: 103,
    name: "Yena Khuyên bạc",
    price: 41,
    tag: "A",
  },
  {
    id: 88,
    name: "Ishar Giấc mơ ngọt ngào",
    price: 44,
    tag: "A",
  },
  {
    id: 31,
    name: "Alice Bé gấu tuyết",
    price: 99,
    tag: "S+",
  },
  {
    id: 36,
    name: "Arduin Tà linh hiệp sỹ",
    price: 99,
    tag: "S",
  },
  {
    id: 39,
    name: "Astrid Siêu sao bóng chày",
    price: 99,
    tag: "S+",
  },
  {
    id: 50,
    name: "Jinna Dạ xoa vương",
    price: 99,
    tag: "S",
  },
  {
    id: 54,
    name: "Lindis Quang thánh tiễn",
    price: 99,
    tag: "S+",
  },
  {
    id: 61,
    name: "Raz Băng quyền quán quân",
    price: 99,
    tag: "S+",
  },
  {
    id: 69,
    name: "Veera Góa phụ giả kim",
    price: 99,
    tag: "S+",
  },
  {
    id: 73,
    name: "Yan nhà chế tác",
    price: 99,
    tag: "S",
  },
  {
    id: 77,
    name: "Zill Dung nham",
    price: 99,
    tag: "S",
  },
  {
    id: 29,
    name: "Aleister Quỷ soái nguyệt tộc",
    price: 104,
    tag: "S",
  },
  {
    id: 45,
    name: "Grakk Mèo thần tài",
    price: 134,
    tag: "S+",
  },
  {
    id: 56,
    name: "Lumburr Cự thần viễn cổ",
    price: 134,
    tag: "S",
  },
  {
    id: 49,
    name: "Ishar Tiểu thư kẹo ngọt",
    price: 139,
    tag: "S",
  },
  {
    id: 76,
    name: "Zill Diệt nguyệt tử sĩ",
    price: 139,
    tag: "S+",
  },
  {
    id: 28,
    name: "Airi Đặc công tử điệp",
    price: 149,
    tag: "S",
  },
  {
    id: 30,
    name: "Aleister Siêu sao bóng rổ",
    price: 149,
    tag: "S+",
  },
  {
    id: 37,
    name: "Arum Linh tượng vu nữ",
    price: 149,
    tag: "S",
  },
  {
    id: 38,
    name: "Arum Quản lý tài năng",
    price: 149,
    tag: "S+",
  },
  {
    id: 40,
    name: "Celica Đếm cừu",
    price: 149,
    tag: "S",
  },
  {
    id: 44,
    name: "Fennik Phi hành gia",
    price: 149,
    tag: "S+",
  },
  {
    id: 46,
    name: "Grakk Tiệc bãi biển",
    price: 149,
    tag: "S+",
  },
  {
    id: 48,
    name: "Hayate Quỷ diện",
    price: 149,
    tag: "S+",
  },
  {
    id: 52,
    name: "Kriknak ST.L-162",
    price: 149,
    tag: "S+",
  },
  {
    id: 57,
    name: "Mganga Pháp sư mèo",
    price: 149,
    tag: "S+",
  },
  {
    id: 58,
    name: "Nakroth BBoy công nghệ",
    price: 149,
    tag: "S+",
  },
  {
    id: 60,
    name: "Omen Ám tử đao",
    price: 149,
    tag: "S+",
  },
  {
    id: 64,
    name: "Sephera Chiêm tinh gia",
    price: 149,
    tag: "S+",
  },
  {
    id: 66,
    name: "Thorne Giả kim thuật sư",
    price: 149,
    tag: "S+",
  },
  {
    id: 67,
    name: "Triệu Vân Cẩm y vệ: Hỏa Long",
    price: 149,
    tag: "S+",
  },
  {
    id: 70,
    name: "Violet Đặc Dị",
    price: 149,
    tag: "S+",
  },
  {
    id: 71,
    name: "Wisp Ếch nhồi bông",
    price: 149,
    tag: "S",
  },
  {
    id: 72,
    name: "Xeniel Tổng lãnh tinh hệ",
    price: 149,
    tag: "S",
  },
  {
    id: 74,
    name: "Zata Thần mặt trời",
    price: 149,
    tag: "S+",
  },
  {
    id: 34,
    name: "Amily Đặc công Nhện đỏ",
    price: 189,
    tag: "S+",
  },
  {
    id: 63,
    name: "Roxie Kèn Ái tình",
    price: 189,
    tag: "Valentine",
  },
  {
    id: 32,
    name: "Alice Tiểu tiên tử",
    price: 199,
    tag: "S+",
  },
  {
    id: 33,
    name: "Allain Bạch kiếm sĩ",
    price: 199,
    tag: "S+",
  },
  {
    id: 35,
    name: "Aoi Hoàng kim công chúa",
    price: 199,
    tag: "S+",
  },
  {
    id: 41,
    name: "Eland'orr Siêu thám tử",
    price: 199,
    tag: "S+",
  },
  {
    id: 42,
    name: "Enzo Chiến binh trăng khuyết",
    price: 199,
    tag: "S",
  },
  {
    id: 43,
    name: "Errol Diệt nguyệt tiên phong",
    price: 199,
    tag: "S",
  },
  {
    id: 47,
    name: "Hayate Bạch vô thường",
    price: 199,
    tag: "S+",
  },
  {
    id: 51,
    name: "Kahlii Kim cô giáo chủ",
    price: 199,
    tag: "S+",
  },
  {
    id: 53,
    name: "Laville Kim quy thần vương",
    price: 199,
    tag: "S+",
  },
  {
    id: 55,
    name: "Lorion Hoả vân tà thần",
    price: 199,
    tag: "S+",
  },
  {
    id: 59,
    name: "Natalya Nữ quái công nghệ",
    price: 199,
    tag: "S+",
  },
  {
    id: 62,
    name: "Raz Mãnh lôi thần quyền",
    price: 199,
    tag: "S+",
  },
  {
    id: 65,
    name: "Tachi Đao khách vô tình",
    price: 199,
    tag: "S+",
  },
  {
    id: 68,
    name: "Triệu Vân Chiến tướng mùa đông",
    price: 199,
    tag: "S",
  },
  {
    id: 75,
    name: "Zephys Hắc vô thường",
    price: 199,
    tag: "S+",
  },
  {
    id: 115,
    name: "D'Arcy Tiến sĩ thiên tài",
    price: 199,
    tag: "S+",
  },
  {
    id: 116,
    name: "Allain Bạch kiếm sĩ",
    price: 199,
    tag: "S+",
  },
  {
    id: 117,
    name: "Natalya Mị muốn đi chơi",
    price: 199,
    tag: "S+",
  },
  {
    id: 118,
    name: "Lorion Quân vương ánh sáng",
    price: 199,
    tag: "S+",
  },
  {
    id: 119,
    name: "Hayate Bóng người dưới trăng",
    price: 199,
    tag: "S+",
  },
  {
    id: 27,
    name: "Yorn Thế tử nguyệt tộc",
    price: 324,
    tag: "SS",
  },
  {
    id: 14,
    name: "Elsu Guitar Tình ái",
    price: 359,
    tag: "Valentine",
  },
  {
    id: 10,
    name: "Airi Kiemono",
    price: 389,
    tag: "SS",
  },
  {
    id: 16,
    name: "Lauriel Thánh quang sứ",
    price: 389,
    tag: "SS",
  },
  {
    id: 19,
    name: "Ngộ Không Siêu việt",
    price: 389,
    tag: "SS",
  },
  {
    id: 21,
    name: "Quillen Đặc công Mãng xà",
    price: 389,
    tag: "SS",
  },
  {
    id: 22,
    name: "Raz Siêu việt",
    price: 389,
    tag: "SS",
  },
  {
    id: 13,
    name: "Điêu Thuyền Thất Tịch Tiên Tử",
    price: 466,
    tag: "SS",
  },
  {
    id: 11,
    name: "Butterfly Kim Ngư thần nữ",
    price: 479,
    tag: "SS",
  },
  {
    id: 12,
    name: "Capheny Kimono",
    price: 479,
    tag: "SS",
  },
  {
    id: 15,
    name: "Lauriel Phi thiên",
    price: 479,
    tag: "SS",
  },
  {
    id: 17,
    name: "Laville Xạ thần tinh vệ",
    price: 479,
    tag: "SS",
  },
  {
    id: 18,
    name: "Liliana Nguyệt Mị Ly",
    price: 479,
    tag: "SS",
  },
  {
    id: 20,
    name: "Omen Đao phủ tận thế",
    price: 479,
    tag: "SS",
  },
  {
    id: 23,
    name: "Richter Kiếm thần Susanoo",
    price: 479,
    tag: "SS",
  },
  {
    id: 24,
    name: "Tulen Tân niên vệ thần",
    price: 479,
    tag: "SS",
  },
  {
    id: 25,
    name: "Violet Thần long tỷ tỷ",
    price: 479,
    tag: "SS",
  },
  {
    id: 26,
    name: "Yena WaVe",
    price: 479,
    tag: "SS",
  },
  {
    id: 3,
    name: "Butterfly Thánh nữ Khởi nguyên",
    price: 558,
    tag: "SS",
  },
  {
    id: 5,
    name: "Ngộ Không Thần Giáp Xích Diễm",
    price: 558,
    tag: "SS",
  },
  {
    id: 6,
    name: "Tel'Annas Thiên Vũ Thần Long",
    price: 558,
    tag: "SS",
  },
  {
    id: 2,
    name: "Bijan Hoàng kim cơ giáp",
    price: 559,
    tag: "SS",
  },
  {
    id: 4,
    name: "Elsu Trấn thiên phi hồ",
    price: 559,
    tag: "SS",
  },
  {
    id: 7,
    name: "Tulen Tiêu Dao Vũ Thần",
    price: 559,
    tag: "SS",
  },
  {
    id: 8,
    name: "Valhein Đệ nhất thần thám",
    price: 559,
    tag: "SS",
  },
  {
    id: 9,
    name: "Yorn Vệ Binh Ngân Hà",
    price: 559,
    tag: "SS",
  },
  {
    id: 107,
    name: "Zata Chí tôn Tà Phượng",
    price: 559,
    tag: "SS",
  },
  {
    id: 108,
    name: "Veera A.I Love you",
    price: 559,
    tag: "SS",
  },
  {
    id: 109,
    name: "Lauriel Vũ khúc miêu ảnh",
    price: 559,
    tag: "SS",
  },
  {
    id: 110,
    name: "Sephera Bách nhạn ngân linh",
    price: 559,
    tag: "SS",
  },
  {
    id: 111,
    name: "Helen Bé Hoa Xuân",
    price: 559,
    tag: "SS",
  },
  {
    id: 112,
    name: "Fennik Phong Tranh Thám Xuân",
    price: 559,
    tag: "SS",
  },
  {
    id: 113,
    name: "Florentino Bá vương âm nhạc",
    price: 559,
    tag: "S-Dreamer",
  },
  {
    id: 114,
    name: "Ngộ Không Tân niên Võ Thần",
    price: 559,
    tag: "SS",
  },
  {
    id: 120,
    name: "Paine Tử xà Bá tước",
    price: 559,
    tag: "SS",
  },
  {
    id: 121,
    name: "Rourke Bách tướng Lão đại",
    price: 559,
    tag: "SS",
  },
  {
    id: 1,
    name: "Raz Chiến thần Muay Thái",
    price: 799,
    tag: "SS",
  },
];
